# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e2cea13a0bf2485b61e369fe8821f27428f6493735b7bc3d83971018e62f543f8246327ad7706c4c83983c0328c46de0d534f5a822e4da8d5a5a33bcdff9828

test:
  secret_key_base: e6bd022da7d062165860225cac312e549966e209b281141d3de8b144c3be40db5e7f997279fab0db8fe0e6d47b2ad29252e67d2546aaddf8f0ce4eb16023fb37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
